name: ai_note_taking_app
description: An AI-powered note-taking application with advanced features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  file_picker: 10.1.9
  path_provider: ^2.1.1
  just_audio: ^0.9.36
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.8.3
  audio_session: ^0.1.18
  sqflite: ^2.3.0
  permission_handler: ^11.0.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env 